### ISSUE TITLE
I REALLY NEED THIS PLUGIN

### ISSUE THREAD

**Issue by anajo333** [stefanscholz/moodle-availability_credit#1]
I am waiting for this plugin, please @stefanscholz  let me know when it will be available

**Comment by stefanscholz** [comment]
@anajo333 Have you seen that we released it? Hope it helps you! Any feedback is appreciated!

**Comment by anajo333** [comment]
Thank you @stefanscholz . the plugin is perfect, But the section credit option is very useful.
I hope you work on it.

Thank you again.
